name: Daily Auto Commits

permissions:
  contents: write

on:
  schedule:
    - cron: '0 11 * * *'  # 11:00 UTC = 1:00 PM Estonian time
  workflow_dispatch:      # allows manual run

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run daily commit script
        run: |
          git config user.name "mtiganik"
          git config user.email "mtiganik@gmail.com"
          python3 script.py
